language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1

before_install: composer global require hirak/prestissimo

install:
    - phpenv config-add ./.travis/php.ini
    - composer install --prefer-dist

script:
    - vendor/bin/phpspec run
    - vendor/bin/phpunit tests/
